apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/TE_FELHASZNALONEVED/library-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__MongoDb
          value: "mongodb://mongodb-service:27017/LibraryDb"
---
apiVersion: v1
kind: Service
metadata:
  name: library-backend-service
spec:
  selector:
    app: library-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  type: ClusterIP