apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-frontend
  template:
    metadata:
      labels:
        app: library-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/TE_FELHASZNALONEVED/library-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: library-frontend-service
spec:
  selector:
    app: library-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer