name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read

    steps:
      - name: 1. Kód letöltése (Checkout)
        uses: actions/checkout@v4

      - name: 2. Bejelentkezés a GitHub Container Registry-be (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Backend Docker image build és push
        uses: docker/build-push-action@v5
        with:
          context: ./BackendApi
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/library-backend:latest
          provenance: false

      - name: 4. Frontend Docker image build és push
        uses: docker/build-push-action@v5
        with:
          context: ./FrontendApp
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/library-frontend:latest
          provenance: false